[tool.poetry]
name = "WenQu"
version = "0.2.0.0"
description = ""
authors = ["丁敬 <dingjing@live.cn>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
langchain = "^0.1.13"
jupyter = "^1.0.0"
ollama = "^0.1.9"
colorama = "^0.4.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
