[tool.poetry]
name = "assistant"
version = "0.1.0"
description = ""
authors = ["丁敬 <dingjing@live.cn>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
langchain = "^0.1.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
